= AsciidoctorJ Screenshot Extension

This AsciidoctorJ extension automates the documentation of your webapp using screenshots.
No more hassles when you change simple settings like CSS or change that button that was too big.
Your documentation stays up to date!

This extension is based on the work of https://github.com/fix/asciidoctor-screenshot[François-Xavier Thoorens]

== Quick reference

Basic usage is a block macro _takeScreenshot_ that points to a URL:
The title of the block macro is used as the caption of the image.

```
.Google Landing page
takeScreenshot::http://google.com[google]
```

Use a block _driveBrowser_ to control the browser (i.e. for filling in a form or doing a login)
The content of the block is passed to http://www.gebish.org/[Geb]. Geb is then taking control of the browser.

```
[driveBrowser]
go "http://google.com"
$("input", name: "q").value("asciidoctor")
waitFor(5){true}
```
== Parameters

=== takeScreenshot

The _takeScreenshot_ block macro has the syntax `takeScreenshot::<url>[<parameters>]` and supports the following parameters
(note: the URL is not needed when the browser was navigated to the page using a _driveBrowser_ block or other means)

name:: an optional unique file name (will be generated otherwise), the screenshot will be called `<name>.png`. This is the first positional parameter.
frame:: Try awesomeness with `iphone5`, `nexus5` or `browser`. This is the second positional parameter.
dimension:: size of the screenshot in the format `<width>x<height>` for instance 800x600. Also the values of 'frame' are supported.
selector:: the CSS-like dom selector to screenshot. Only this will be part of the image. For instance `div #login_window`.

Note: it is not allowed to set both 'frame' and 'dimension' or 'frame' and 'selector' for a screenshot.
Note: `takeScreenshot::http://google.com[google]` and `takeScreenshot::http://google.com[name=google]` are equivalent.

=== driveBrowser

The _driveBrowser_ block supports the following parameters:

dimension:: size of the screenshot in the format `<width>x<height>` for instance 800x600. Also the values of 'frame' are supported. This is the first positional parameter.

== Examples

```
.The Google landing page
takeScreenshot::http://google.com[google]
```

```
[driveBrowser]
$("input", name: "q").value("asciidoctor")
waitFor(5){true}
```

```
.Some propositions should appear
takeScreenshot::[frame=BROWSER]
```

```
[driveBrowser, dimension=iphone5]
$("h3.r a").click()
```

```
.Look Ma, it's Nexus 5!
takeScreenshot::[frame=nexus5]
```
